# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb14b38e7f7daf189be4cdd2550324118d8f954841bb97e3674a47ec4d6fd549722221a1f4bc44afed17be81ec7bb70f816bf2cc5784de2bc07fcf0d4d101fcd

test:
  secret_key_base: 4c2a7a17b8c154522eeb6c67bf5e86037268c7052c2945d6aeed802b2c54a8682168e15d4f00189f302306fd7542aa95f3df7cabb65f2ec600488da27f112a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
